language: ruby
sudo: false
rvm:
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3

before_install:
  - gem update --system
  - gem --version

gemfile:
  - Gemfile

notifications:
  email: false

addons:
    code_climate:
        repo_token: 81d8be15cbe7dcbba348c6d7671681e03058337dcbe725e66e2e363d88a228ac
