language: ruby
rvm:
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.2
  - 2.1
  - 2.0
  - jruby

before_install:
  - gem update --system
  - gem --version

gemfile:
  - Gemfile

notifications:
  email: false
